# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

# Required tools
require 'capistrano/composer'
require 'capistrano/cachetool'

# Antistatique custom tasks
require 'capistrano/antistatique/wordpress'
require 'capistrano/antistatique/maintenance'
require 'capistrano/antistatique/httpauth'

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('config/capistrano/tasks/*.rake').each { |r| import r }
