services:
  dev:
    hostname: dev
    build:
      args:
        composer_token: MUST BE SET
        # user: <YOUR USER ID> for windows
    ports:
      - "8080:80"
    environment:
      WP_HOME: "http://localhost:8080"
      WP_SITEURL: "http://localhost:8080/wp"
      # ACF_PRO_LICENSE: CAN ALSO BE SET IN ADMIN
    # volumes:
    #   # WordPress
    #   - ./composer.json:/var/www/composer.json
    #   - ./composer.lock:/var/www/composer.lock
    #   # Theme
    #   - ./web/app/themes/eldora-theme:/var/www/web/app/themes/eldora-theme
    #   - ./web/app/languages:/var/www/web/app/languages
    #   # Custom Guttenberg Plugin
    #   - ./web/app/custom-plugins:/var/www/web/app/custom-plugins
    #   # Files
    #   - ./web/app/uploads/:/var/www/web/app/uploads

  # Database
  # db:
  #   ports:
  #     - "3306:3306"

  # Mail
  # mail:
  #   ports:
  #     - "1080:1080"
