events {
    worker_connections 1024;
}

http {
    # 1. Normalisation du header Accept
    map $http_accept $image_format {
        "~*avif"    "avif";
        "~*webp"    "webp";
        default     "standard";
    }

    # 2. Nouvelle clé de cache
    proxy_cache_key "$scheme$proxy_host$request_uri-$image_format";

    # 3. Configuration du stockage
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=img_cache:10m max_size=1g inactive=7d use_temp_path=off;

    server {
        listen 80;
        server_name resize.chapi.ch;

        location / {
            # 4. Transmission à l'upstream
            proxy_set_header Accept $http_accept;
            proxy_pass http://imgproxy:8080;

            # 5. Activation du cache
            proxy_cache img_cache;
            proxy_cache_valid 200 302 30d;

            # 6. Headers de débogage
            add_header X-Proxy-Cache $upstream_cache_status;
            add_header Content-Type $upstream_http_content_type;

            # 7. Header HTTP standard pour la négociation de contenu
            add_header Vary "Accept";
        }
    }
}