import React, { useState } from "react";
import useDimensions from "react-cool-dimensions";
import { motion } from "framer-motion";
import Image from "next/legacy/image";
import PropTypes from "prop-types";
import { isNil } from "ramda";

// Mirror of luxury-tribune-backend/web/app/themes/luxury-tribune/config/images.php
const ratios = {
  "2x1": [1640, 820],
  "16x9": [1640, 820], // Legacy ratio → design define it as 2x1
  "1x1": [1640, 1640],
  "3x2": [1640, 1093],
  "9x16": [922, 1640],
  "10x13": [1262, 1640],
};

const FadeInImage = ({ src, alt, width, height, ...props }) => {
  const [loaded, setLoaded] = useState(false);
  const { observe, width: currentWidth } = useDimensions();

  const handleLoad = (e) => {
    // Ensure we're listening the correct img element generated by next/image
    if (e.target.srcset) {
      setLoaded(true);
    }
  };

  if (isNil(src)) {
    return null;
  }

  const ext = src.split(".").pop();

  if (isNil(width) || isNil(height)) {
    return (
      <div className="fix-image">
        <Image
          src={src.replace(/-\d+x\d+.\w+$/g, `.${ext}`)}
          alt={alt}
          onLoad={handleLoad}
          layout="fill"
          objectFit="contain"
          quality={90}
          className="w-full"
          {...props}
        />
      </div>
    );
  }

  const [w, h] = ratios[`${width}x${height}`];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={loaded && { opacity: 1 }}
      ref={observe}
    >
      <Image
        src={src
          .replace(/-\d+x\d+.\w+$/g, `.${ext}`)
          .replace("-scaled.", ".")
          .replace(`.${ext}`, `-${w}x${h}.${ext}`)}
        alt={alt}
        width={width}
        height={height}
        onLoad={handleLoad}
        sizes={!isNil(currentWidth) ? `${Math.round(currentWidth)}px` : "100vw"}
        layout="responsive"
        quality={90}
        {...props}
      />
    </motion.div>
  );
};

FadeInImage.propTypes = {
  src: PropTypes.string,
  alt: PropTypes.string,
  width: PropTypes.number,
  height: PropTypes.number,
};

FadeInImage.defaultProps = {};

export default FadeInImage;
